spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-idle: 5
      max-active: 10
      max-wait: 10000
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 1 from dual
#    url: jdbc:mysql://172.25.20.169:3306/buaa_robot_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: robot
#    password: 0000
    url: jdbc:mysql://rm-bp11j369b99dlh52zko.mysql.rds.aliyuncs.com:3306/buaa_robot_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: robot
    password: Admin!@01

out:
  weatherUrl: http://wthrcdn.etouch.cn/weather_mini?city=
  translateUrl: http://fanyi.youdao.com/openapi.do?keyfrom=xinlei&key=759115437&type=data&doctype=json&version=1.1&q=