spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      max-idle: 5
      max-active: 10
      max-wait: 10000
      test-while-idle: true
      test-on-borrow: true
      validation-query: select 1 from dual
#    url: jdbc:mysql://172.25.20.169:3306/buaa_robot_db?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: robot
#    password: 0000
    url: jdbc:mysql://10.96.238.10:10027/taotieRawBaseSt?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: user_taotieRawBaseSt
    password: cgmngapdmphidpeg

